version: '3'
services:
  db:
    image: postgres:12.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: map-egypt@postgres
      POSTGRES_DB: map_egypt
    ports:
      - "5004:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 180s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  site:
    build: ./map-egypt.github.io/.
    ports:
      - "5000:80"
  api:
    build: ./api/.
    env_file:
      - ./api/.env
    ports:
      - "5001:5000"
    volumes:
      - uploaded:/app/uploaded
      
  admin:
    build: ./admin/.
    ports:
      - "5002:80"
volumes:
  uploaded:
