version: '3'
services:
  db:
    image: postgres:12.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: map-egypt@postgres
      POSTGRES_DB: map_egypt
    ports:
      - "9044:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 180s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
  site:
    build: ./map-egypt.github.io/.
    ports:
      - "9023:80"
    restart: always
  api:
    build: ./api/.
    env_file:
      - ./api/.env
    ports:
      - "9011:5000"
    volumes:
      - ./uploaded:/app/uploaded
    restart: always
  admin:
    build: ./admin/.
    ports:
      - "9021:80"
    restart: always